### ISSUE TITLE
Get twoppp to work with new df3d

### ISSUE THREAD

**Issue by jasper-tms** [NeLy-EPFL/twoppp#24]
After just changing `deepfly.CameraNetwork` to `pyba.CameraNetwork`, I was able to use twoppp to run df3d, using the latest version of df3d from the master branch. The messages that were printed seemed to indicate df3d ran successfully (and indeed it generated output files), but then at the end twoppp got confused by the different filenames produced by the latest df3d code:

```
Working in /mnt/nas2/JSP/220829_C30xCI9/Fly3/002_rightT1vol/behData/images
Default camera ordering found: [6, 5, 4, 3, 2, 1, 0]
100%|███████████████████████████████████████████████████████████████████████████████████████████| 9187/9187 [57:04<00:00,  2.68it/s]
Triangulation skipped.
Saved results at: /mnt/nas2/JSP/220829_C30xCI9/Fly3/002_rightT1vol/behData/images/df3d/df3d_result__mnt_nas2_JSP_220829_C30xCI9_Fly3_002_rightT1vol_behData_images.pkl
/home/phelps/.virtualenvs/twoppp-py37-tf24-newdf3d/lib/python3.7/site-packages/scipy/sparse/lil.py:518: FutureWarning: future versions will not create a writeable array from broadcast_array. Set the writable flag explicitly to avoid this warning.
  if not x.flags.writeable:
   Iteration     Total nfev        Cost      Cost reduction    Step norm     Optimality
       0              1         2.1581e+07                                    7.71e+07
       1              2         2.4827e+06      1.91e+07       3.09e+01       5.74e+06
       2              3         2.4255e+06      5.72e+04       5.49e+00       1.49e+05
       3              4         2.4241e+06      1.46e+03       8.88e-01       4.21e+04
       4              5         2.4240e+06      1.39e+02       2.87e-01       1.54e+04
`ftol` termination condition is satisfied.
Function evaluations 5, initial cost 2.1581e+07, final cost 2.4240e+06, first-order optimality 1.54e+04.
Saved results at: /mnt/nas2/JSP/220829_C30xCI9/Fly3/002_rightT1vol/behData/images/df3d/df3d_result__mnt_nas2_JSP_220829_C30xCI9_Fly3_002_rightT1vol_behData_images.pkl
Tue Dec  6 22:47:40 2022 postprocessing df3d for trial: /mnt/nas2/JSP/220829_C30xCI9/Fly3/002_rightT1vol
TASK MANAGER clean up: removing tasks from _tasks_running.txt
Traceback (most recent call last):
  File "./run.py", line 21, in <module>
    main()
  File "./run.py", line 18, in main
    task_manager.run()
  File "/home/phelps/repos/nely-new/twoppp/twoppp/run/taskmanager.py", line 230, in run
    success = self.execute_next_task()
  File "/home/phelps/repos/nely-new/twoppp/twoppp/run/taskmanager.py", line 214, in execute_next_task
    result = self.task_collection[task_name].run(fly_dict=next_todo, params=self.params)
  File "/home/phelps/repos/nely-new/twoppp/twoppp/run/tasks.py", line 973, in run
    preprocess._post_process_pose()
  File "/home/phelps/repos/nely-new/twoppp/twoppp/pipeline.py", line 983, in _post_process_pose
    result_prefix=result_prefix)
  File "/home/phelps/repos/nely-new/twoppp/twoppp/behaviour/df3d.py", line 144, in postprocess_df3d_trial
    pose_result = find_file(df3d_dir, name="pose_result*", file_type="pose result file")
  File "/home/phelps/repos/nely-new/twoppp/twoppp/utils/__init__.py", line 225, in find_file
    raise FileNotFoundError(f"No {file_type} file found in {directory}")
FileNotFoundError: No pose result file file found in /mnt/nas2/JSP/220829_C30xCI9/Fly3/002_rightT1vol/behData/images/df3d
```

I'll continue investigating when I can.

**Comment by jonasfbraun** [comment]
I updated the code and installation procedure such it installs the new version of df3d and runs the updated version of df3d postprocessing.
I was able to run everything, but feel free to test it also!
